Do not update forbidden fields for statefulset (#75)
Every time I upgrade this helm chart I got this error
```
Error: UPGRADE FAILED: cannot patch "vaultwarden" with kind StatefulSet: StatefulSet.apps "vaultwarden" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
```

Let's not put all the labels from helper, because they contain also chart version which changes on every upgrade
```
    volumeClaimTemplates:
      - metadata:
          name: vaultwarden-data
          labels:
-             helm.sh/chart: vaultwarden-0.20.0
+             helm.sh/chart: vaultwarden-0.22.1
              app.kubernetes.io/name: vaultwarden
              app.kubernetes.io/instance: vaultwarden
-             app.kubernetes.io/version: "1.30.1"
+             app.kubernetes.io/version: "1.30.3"
              app.kubernetes.io/managed-by: Helm
```

Fixes: https://github.com/guerzon/vaultwarden/issues/58

* Update charts/vaultwarden/Chart.yaml

Co-authored-by: Nicholas Santiago <nicholas.santiago@gmail.com>

---------

Co-authored-by: Nicholas Santiago <nicholas.santiago@gmail.com>